import time
import colorama
from colorama import Fore, Back, Style
colorama.init()
print(Fore.RED)
print("""================================

##############################
#        STRONG ATTACK       #
#                            #
#   ===[ Jroken ]===         #
#                            #
#       ===[ ByTegn ]===     #
#                            #
##############################

İnstagram : jrok3n 
İnstagram : ozekk35

=================================""")
print()
print(Fore.YELLOW)
tel = input("Tel No : " ) 
time.sleep(0.2)
print ("Bumlanıcak No ==> "+tel)
input("Onaylıyormusunuz : " )
time.sleep(0.4)
print(Fore.YELLOW)
print("Saldırı Başlıyor") 
time.sleep(0.2)
print ("[ Araçlar Kuruluyor  ] 0% ")
time.sleep(3)
print ("[=====               ] 25%")
time.sleep(3)
print ("[==========          ] 50%")
time.sleep(3)
print ("[===============     ] 75%")
time.sleep(3)
print ("[====================] 100%")
time.sleep(1)
print(Fore.GREEN)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print("Getting Hacked ==> "+tel)
time.sleep(0.1)
print (Fore.BLUE)
print("Veriler Aktarılıyor")
time.sleep(3)
print(Back.RED)
print("Security = %0")
time.sleep(0.75)
print("İşlem = Başarılı")
time.sleep(0.75)
print("""Açık Portlar = 
21/tcp   open ftp
22/tcp   closed ssh
23/tcp   open telnet
80/tcp   open   http
110/tcp  open pop3
143/tcp  closed imap
443/tcp  open   https
3389/tcp closed ms-wbt-server""")
